server:
  port: 8081

spring:
  application:
    name: platinabank-cards
  config:
    import: optional:configserver:http://localhost:8071/
  profiles:
    active: prod
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: cardsDB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: platinabank-cards
    description: "Platina Bank Cards Application"
    version: 1.0.4

logging:
  level:
    com:
      platinabank:
        cards: DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"