server:
  port: 8080

spring:
  application:
    name: platinabank-accounts
  config:
    import: optional:configserver:http://localhost:8071/
  profiles:
    active: prod
  data:
    mongodb:
      uri: mongodb://localhost:27017/
      database: accountsDB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

info:
  app:
    name: platinabank-accounts
    description: "Platina Bank Accounts Application"
    version: 1.0.5

