server:
  port: 8080

spring:
  application:
    name: platinabank-accounts
  config:
    import: optional:configserver:http://localhost:8071/
  profiles:
    active: prod
  data:
    mongodb:
      uri: mongodb+srv://root:root@platina-bank.8evcdpv.mongodb.net/
      database: accountsDB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true