apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
  labels:
    app: platinabank-accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platinabank-accounts
  template:
    metadata:
      labels:
        app: platinabank-accounts
    spec:
      containers:
        - name: platinabank-accounts
          image: vulka9n/platinabank-accounts:v11
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: platinabank-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: platinabank-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: platinabank-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: platinabank-configmap
                  key: SPRING_DATA_MONGODB_URI
---
apiVersion: v1
kind: Service
metadata:
  name: platinabank-accounts
spec:
  selector:
    app: platinabank-accounts
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
