apiVersion: apps/v1
kind: Deployment
metadata:
  name: cards-deployment
  labels:
    app: platinabank-cards
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platinabank-cards
  template:
    metadata:
      labels:
        app: platinabank-cards
    spec:
      containers:
        - name: platinabank-cards
          image: vulka9n/platinabank-cards:v8
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: platinabank-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: platinabank-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: platinabank-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: platinabank-configmap
                  key: SPRING_DATA_MONGODB_URI
---
apiVersion: v1
kind: Service
metadata:
  name: platinabank-cards
spec:
  selector:
    app: platinabank-cards
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
