apiVersion: apps/v1
kind: Deployment
metadata:
  name: platinabank-configserver-deployment
  labels:
    app: platinabank-configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platinabank-configserver
  template:
    metadata:
      labels:
        app: platinabank-configserver
    spec:
      containers:
        - name: platinabank-configserver
          image: vulka9n/platinabank-configserver:v3
          ports:
            - containerPort: 8071
---
apiVersion: v1
kind: Service
metadata:
  name: platinabank-configserver
spec:
  selector:
    app: platinabank-configserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
