apiVersion: apps/v1
kind: Deployment
metadata:
  name: gatewayserver-deployment
  labels:
    app: platinabank-gatewayserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platinabank-gatewayserver
  template:
    metadata:
      labels:
        app: platinabank-gatewayserver
    spec:
      containers:
        - name: platinabank-gatewayserver
          image: vulka9n/platinabank-gatewayserver:v6
          ports:
            - containerPort: 9090
          env:
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: platinabank-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: platinabank-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
              valueFrom:
                configMapKeyRef:
                  name: platinabank-configmap
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
---
apiVersion: v1
kind: Service
metadata:
  name: platinabank-gatewayserver
spec:
  selector:
    app: platinabank-gatewayserver
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
