services:
  network-deploy-service:
    networks:
      - platinabank-network

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: rabbit
      JAVA_TOOL_OPTIONS: "-javaagent:/app/libs/opentelemetry-javaagent-1.31.0.jar"
      OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo:4317
      OTEL_METRICS_EXPORTER: none

  microservice-gateway-config:
    extends:
      service: microservice-base-config
    environment:
      SPRING_CONFIG_IMPORT: "configserver:http://platinabank-configserver:8071/"
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: "http://platinabank-eurekaserver:8761/eureka"

  microservice-total-config:
    extends:
      service: microservice-gateway-config
    depends_on:
      platinabank-configserver:
        condition: service_healthy
      platinabank-eurekaserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATA_MONGODB_URI: "mongodb+srv://root:root@platina-bank.8evcdpv.mongodb.net/"
