services:
  network-deploy-service:
    networks:
      - platinabank-network

  microservice-base-config:
    extends:
      service: network-deploy-service
    deploy:
      resources:
        limits:
          memory: 700m
    environment:
      SPRING_RABBITMQ_HOST: rabbit

  microservice-configserver-config:
    extends:
      service: microservice-base-config
    depends_on:
      platinabank-configserver:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_CONFIG_IMPORT: "configserver:http://platinabank-configserver:8071/"
